session_name: experiments
shell_command_before: "conda activate experiments"
shell_command_after: "sleep 2; clear"
windows:
  - window_name: code
    focus: true
    start-directory: ./
    panes:
      - shell_command:
        - nvim
  - window_name: cmd
    start-directory: ./
    panes:
      - shell_command:
        - ls
  - window_name: srv
    start-directory: ./
    panes:
      - shell_command:
        - ls
  - window_name: files
    panes:
      - shell_command:
        - clear
  - window_name: notes
    panes:
      - shell_command:
        - emacs README.org
